
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/toDO
        password: Emenike@16
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            format-sql: true